### PR TITLE
fix issue #24 - site is small on the mobile screen

### PR DESCRIPTION
**Pull request by bLaCkwEw**
Fixed issue #24 
I'd like to suggest rewritting the CSS of the website and making it responsive from the start (ie: not have different CSS files for desktop and mobile).

### CODE REVIEW

**Comment by xyrelljoi** [comment]
hi! @bLaCkwEw 😄 can you send us a screenshot of the output?

**Comment by bLaCkwEw** [comment]
Here you go @xyrelljoi 

Screen Shot 2021-07-27 at 10 35 54

**Comment by xyrelljoi** [comment]
that's great @bLaCkwEw ✨  however, our social media links, takes slight spaces. making it longer to scroll. would it be possible if you can **aligned them horizontally*?
ex.
image

**Comment by bLaCkwEw** [comment]
I'll try to do that and update you with the results.

**Comment by xyrelljoi** [comment]
cool @bLaCkwEw let us know if you're unable to fix it. we can still merge this request without that 😄

**Comment by bLaCkwEw** [comment]
Does this work, @xyrelljoi? 
It will also wrap any new items on a new line in case you add more socials.

Screen Shot 2021-07-27 at 11 08 44

**Review by xyrelljoi — APPROVED** [review]

**Comment by xyrelljoi** [comment]
awesomeee ❤️ thank you for contributing @bLaCkwEw ✨

**Pull request merged**
